### PR TITLE
Add a single line expectation with an implicit subject

### PR DESCRIPTION
**Pull request by sungwoncho**

### CODE REVIEW

**Comment by paveldruzyak** [comment]
@sungwoncho why `iti`? and will be good to add new syntax too, like `it { is_expected.not_to be_empty }`

**Comment by sungwoncho** [comment]
I've been using it as `iti` because a plugin I used to use in Sublime defined it as such. I added the syntax you suggested.

**Comment by paveldruzyak** [comment]
we already use prefix `its` on line 84. Maybe `itis`?

**Comment by sungwoncho** [comment]
Oops. Didn't see the duplicate.

**Comment by ryansobol** [comment]
@sungwoncho which plugin is that?

**Comment by paveldruzyak** [comment]
:+1:

**Pull request merged**
