### PR TITLE
Add more keywords

### PR DESCRIPTION
**Pull request by paveldruzyak**
closes #26 #28

### CODE REVIEW

**Comment by paveldruzyak** [comment]
@dkniffin @Cosaquee I combined yours PR in this PR. Please review it and add your opinion.

@ryansobol please, also look to this PR.

**Comment by paveldruzyak** [comment]
@lordjavac looks like you care about this plugin, so I will welcome your opinion about this PR also

**Comment by lordjavac** [comment]
I think it looks like a good addition to the package. I don't personally use most of the keywords added, but it's nice to have them there for those who do.

**Comment by Cosaquee** [comment]
:+1:

**Comment by dkniffin** [comment]
Any chance you can post a before and after screenshot, like @Cosaquee did in his PR?

**Comment by dkniffin** [comment]
The only thing I'd like changed is to move `let`, and `subject` into their own matcher, with the `variable` name, like I did [here](https://github.com/paveldruzyak/language-rspec/pull/26/files#diff-886e818932d15207f8ae939a7a6f9d2dR19). That really helps those stand out. It's especially useful for `subject` because you can easily find where the main thing that's being tested is actually being called.

**Comment by Cosaquee** [comment]
what is the status of this PR ? I would really like this to be merged : )

**Comment by paveldruzyak** [comment]
I'm not sure about this PR.

# before:
example_spec_rb_ __users_paveldruziak_projects_active_atom_language-rspec

# after:
example_spec_rb_ __users_paveldruziak_projects_active_atom_language-rspec

**Comment by dkniffin** [comment]
It looks good, except my comment from above:

> The only thing I'd like changed is to move `let`, and `subject` into their own matcher, with the `variable` name, like I did [here](https://github.com/paveldruzyak/language-rspec/pull/26/files#diff-886e818932d15207f8ae939a7a6f9d2dR19). That really helps those stand out. It's especially useful for `subject` because you can easily find where the subject of the test is actually being called.

**Comment by paveldruzyak** [comment]
@dkniffin this how it's look like with your changes. Do you think it's better?
example_spec_rb_ __users_paveldruziak_projects_active_atom_language-rspec

**Comment by dkniffin** [comment]
Yep, I like that much better.

**Comment by dkniffin** [comment]
This PR looks good to me. @paveldruzyak Can we merge this?

**Comment by paveldruzyak** [comment]
sorry, but I think it's too colorful with changes

**Pull request closed without merging**
