### PR TITLE
Change snippet quote types to double

### LINKED ISSUE #9: Add setting for preferred quotes
Could you possibly add a setting where one could prefer, maybe, single quotes over double quotes when autocompleting?

I find myself replacing double quotes with single quotes all the time, which is a bit annoying to me.

Thank you,

### PR DESCRIPTION
**Pull request by dsandstrom**
I like using apostrophes in my test messages and got tired of manually changing quotes whenever I write `doesn't`.  Should kind of fix #9.  I might have missed some, but got the snippets that I use the most.   Let me know if something needs to change.

### CODE REVIEW

**Comment by paveldruzyak** [comment]
I think it's good idea. @ryansobol what you think?

**Comment by ryansobol** [comment]
Hey @dsandstrom,

I totally hear you. The reason this package defaults to single quotes is to follow the best practices of the Ruby community as defined by the [Ruby Style Guide](https://github.com/bbatsov/ruby-style-guide) and as implemented by the [Rubocop](https://github.com/bbatsov/rubocop) gem. For more information about that decision, please see issue #11.

That said, I'm very much a fan of personal preference. I'd love to see this package support [custom configuration](https://atom.io/docs/api/v0.187.0/Config) so a user could use snippets with either single or double quoted strings. How does that sound to everyone?

**Comment by dsandstrom** [comment]
@ryansobol Thanks for the feedback and explanation.  Normally, I'd agree with you and say that single quotes are the way to go.  However, I feel that double quotes work better for me when writing RSpec.

As for configuration options, that doesn't seem easily done right now.  Variables can't be used in Atom's cson files.  Maybe we could have separate files for single/double quote snippets.  But, as the [ documentation](https://atom.io/docs/v0.186.0/creating-a-package#snippets) states: 

> All files in the directory are automatically loaded, unless the package.json supplies a snippets key. As with all scoped items, snippets loaded later take precedence over earlier snippets when two snippets match a scope with the same specificity.

Another option would be to use the *package.json* snippets key to dynamically load snippets based on the user's configuration.  I'm not exactly sure how to do this and doubt it's worth the effort

**Comment by dsandstrom** [comment]
Closing this.

**Pull request closed without merging**
